"""add two fields in user model

Revision ID: 297ab223b8b7
Revises: 30d0c8ee8f6a
Create Date: 2018-05-22 19:25:04.925892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297ab223b8b7'
down_revision = '30d0c8ee8f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
